app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Email, Length, EqualTo
from wtforms import TextAreaField

# 用户修改资料类
class EditUserForm(FlaskForm):
    email = StringField(label='邮箱', validators=[DataRequired(), Email(), Length(1, 128)])
    name = StringField(label='昵称', validators=[DataRequired(), Length(1, 128)])
    location = StringField(label='位置', validators=[DataRequired(), Length(1, 64)])
    about_me = TextAreaField(label='签名', validators=[DataRequired(), Length(1, 256)])
    password = PasswordField(label='密码')
    password_again= PasswordField(label='确认密码', validators=[EqualTo('password', '两次密码不一致')])
    submit = SubmitField(label='确认编辑')

# 管理员资料修改
class PostNewsForm(FlaskForm):
    title = StringField(label='标题', validators=[DataRequired(), Length(1, 128)])
    body = TextAreaField(label='正文', validators=[DataRequired()])
    private = BooleanField(label='私有', default=False)
    submit = SubmitField(label='发表')

# 发表评论
class PostCommentForm(FlaskForm):
    body = TextAreaField(label="", validators=[DataRequired()])
    submit = SubmitField(label="发表")


app/main/__init__.py
# 导入蓝本类
from flask import Blueprint
main = Blueprint('main', __name__)

# 导入views,errors模块
from . import views, errors

app/main/views.py
from flask import render_template, request,url_for, redirect
from flask import abort

from app import db
from . import main

from flask_login import login_required

# 主页
@main.route('/')
def index():
    # render_template会去app/templates下找模板
    return render_template('main/index.html')

# 个人主页，没有认证就不能访问
@main.route('/user_info')
@login_required
def user_info():
    # 访问视图用户资料视图
    id = request.args.get('id')
    if id is None:
        abort(404)
    user = User.query.filter_by(id = id).first()
    if user is None:
        abort(404)
    return render_template('main/user_info.html', user=user)

@main.route('/favicon.ico')
def favicon():
    return 'ok'

# 更改个人信息表单
from app.models import User
from .forms import EditUserForm
# current_user根据cookie查找用户id，保cookie存了登录信息：登录状态
from flask_login import current_user
# methods提交表单
@main.route('/edit_user', methods=['GET', 'POST'])
def edit_user():
    form = EditUserForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.about_me = form.about_me.data
        current_user.location = form.location.data
        if len(form.password.data) != 0:
            current_user.password = form.password.data
        db.session.add(current_user)
        db.session.commit()
        return redirect(url_for('.user_info', id=current_user.id))

    form.email.data = current_user.email
    form.name.data = current_user.name
    # form.password.data = '*******'
    # form.password_again.data = '*******'
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('main/edit_user.html', form=form)

# 全部新闻
from app.models import Follow
#http://127.0.0.1/all_news?page=4
#http://127.0.0.1/all_news
@main.route('/all_news')
def all_news() :
    # ans = News.query.all()
    # 分页对象
    page = request.args.get('page', type=int, default=1)
    # 获取cookie中follow_flag的值 '0' '1'
    follow_flag = request.cookies.get('follow_flag', default='0')

    # 所有的
    if follow_flag == '0':
        # order_by(News.id.desc())降序
        paginate = News.query.order_by(News.id.desc()).paginate(page=page, per_page=5, error_out=False)
    else:
        # followeds = Follow.query.filter_by(follower_id=current_user.id).all()
        # users = [f.followed for f in followeds]
        # news = [u.news.all() for u in users]
        # 联结查询：多张表一起查询
        # 本质：把符合条件的记录查询出来做一张虚拟表
        query = News.query.join(Follow, Follow.followed_id == News.user_id).filter(
            Follow.follower_id == current_user.id)
        paginate = query.order_by(News.id.desc()).paginate(page=page, per_page=5, error_out=False)

    # 用到的表   users follows news
    # 1.current_user.id == follows.follower.id
    # 2.news.user_id == follows.followed.id

    #return render_template('main/all_news.html', ans=ans)
    #分页对象中有什么？
    #1.表示上一页页码的prev_num
    #2.表示下一页页码的next_num
    #3.表示上一页的分页对象的prev
    #4.表示下一页的分页对象的next
    #5.表示是否有上一页的has_prev
    #6.表示是否有下一页的has_next
    #7.表示总共的页数的pages
    #8.表示总共的元素数量的total_num
    #9.用来设置分页数字样式的iter_pages
    #10.用来表示当前分页的所有元素的items

    # 渲染模板，把all_news.html的所有变量替换、把python代码执行，变成一个纯静态页面
    return render_template('main/all_news.html', paginate=paginate)

# 发表文章
from .forms import PostNewsForm
from app.models import News
@main.route('/post_news', methods = ['GET', 'POST'])
@login_required
def post_news():
    form = PostNewsForm()
    if form.validate_on_submit():
        news = News()
        news.body = form.body.data
        news.private = form.private.data
        news.title = form.title.data
        news.user_id = current_user.id
        db.session.add(news)
        db.session.commit()
        return redirect(url_for('.all_news'))
    return render_template('main/post_news.html', form=form)

# 文章 | 评论
from .forms import PostCommentForm
from app.models import Comment
from random import randint
from ..decorators import decorator_permission
from app.models import Permission
@main.route('/news', methods = ["GET","POST"])
@decorator_permission(Permission.COMMENT)
def news():
    has_form = request.args.get("has_form", default=False)
    nid = request.args.get('nid')
    if nid is None:
        abort(404)
    news = News.query.filter_by(id = nid).first()
    if news is None:
        abort(404)
    comment = news.comment.all()
    # 评论表单
    form = PostCommentForm()
    if form.validate_on_submit():
        comment = Comment()
        comment.body = form.body.data
        comment.title = "{}评论{}".format(current_user.name, news.user.name)
        comment.user = current_user
        comment.news = news
        comment.color = randint(1, 4)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for("main.news", nid=nid))

    return render_template("main/news.html", news = news, form = form, has_comment=has_form, comment=comment)

# 删除评论
@main.route("/delete_comment")
def delete_comment():
    cid = request.args.get("cid")
    if cid is None:
        abort(404)
    comment = Comment.query.filter_by(id=cid).first()
    nid = comment.news_id
    if current_user == comment.user or current_user.has_permission(Permission.MODE_COMMENT):
        db.session.delete(comment)
        db.session.commit()
    return redirect(url_for("main.news",nid = nid))

# 删除文章
@main.route('/delete_news')
@login_required
def delete_news():
    nid = request.args.get('nid')
    if nid is None:
        abort(404)
    news = News.query.filter_by(id = nid).first()
    if news is None:
        abort(404)
    if current_user == news.user or current_user.is_admin():
        db.session.delete(news)
        db.session.commit()
    return redirect(url_for('main.all_news'))

from app.decorators import decorator_permission
from app.models import Permission
# 关注用户
@main.route('/follow')
@decorator_permission(Permission.FOLLOW)
def follow():
    id = request.args.get('id')
    if id is None:
        abort(404)
    user = User.query.filter_by(id=id).first()
    if user is None:
        abort(404)
    current_user.follow(user)
    return redirect(url_for('main.user_info', id=user.id))

# 取消关注用户
@main.route('/unfollow')
@decorator_permission(Permission.FOLLOW)
def unfollow():
    id = request.args.get('id')
    if id is None:
        abort(404)
    user = User.query.filter_by(id=id).first()
    if user is None:
        abort(404)
    current_user.unfollow(user)
    return redirect(url_for('main.user_info', id=user.id))

# 查看粉丝
@main.route('/all_followers')
def all_followers():
    id = request.args.get('id')
    if id is None:
        abort(404)
    user = User.query.filter_by(id=id).first()
    if user is None:
        abort(404)

    #通过反向关系followers得到的全是Follow对象
    #这些对象的特点是：followed_id都等于user.id
    #follower_id是关注user的用户的id---->follower是user对象
    afs = user.followers.all()

    users = [f.follower for f in afs]

    return render_template('main/all_followers.html', users=users)

# 所有诗词，这个函数要修改浏览器中的cookie
# make_response构造一个响应
from flask import make_response
@main.route('/set_all_news_flag')
def set_all_news_flag():
    response = make_response(redirect(url_for('.all_news')))
    response.set_cookie('follow_flag', '0', 60*60*24)
    # 返回一个字符串
    return response

# 关注诗词
@main.route('/set_follow_news_flag')
def set_follow_news_flag():
    response = make_response(redirect(url_for('.all_news')))
    response.set_cookie('follow_flag', '1', 60 * 60 * 24)
    return response








app/templates/main/all_followers.html
{% extends 'base.html' %}

{% block page_content %}
<h2><small>欢迎!</small>&nbsp;&nbsp;{{current_user.name}}</h2>
{% endblock %}

{% block page_content1 %}

    {% for user in users %}
    <div class="alert alert-success" role="alert">
            我的昵称：{{user.name}}
            <a class="btn badge"  style="color:#5628ff">粉丝{{ user.followers.count() }}</a><br>
            邮箱：{{user.email}}<br>
            签名：{{user.about_me}}
    </div>

    {% endfor %}
{% endblock %}

app/templates/main/all_news.html
<!--在app/templates下找base.html-->
{% extends 'base.html' %}

{% block page_content%}
    <h2><small>Dear</small>&nbsp;&nbsp;{{current_user.name}}</h2>
    <!-- 发诗词-->
    <div class="page-header">
        <a href="{{url_for('main.post_news')}}" class="btn btn-default">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </a>
        <a href="{{url_for('main.set_all_news_flag')}}" class="btn btn-info">所有诗词</a>
        <a href="{{url_for('main.set_follow_news_flag')}}" class="btn btn-warning">关注诗词</a>
    </div>
{% endblock %}

{% block page_content1 %}
    {% for news in paginate.items %}
        <div class="page-header">
            <font size="4" color="#191970" style="margin-right: 300px;">
                <a href="{{url_for('main.news', nid=news.id)}}">
                    {{news.title}}
                </a>
        </font>
        <!-- 用户 -->
        <font size="3" color="black" style="float:right; width:100px;">
            <a href="{{url_for('main.user_info', id=news.user.id)}}">
                {{news.user.name}}
            </a>
        </font>

        <br>
        <!-- 文章 -->
        <font size="2" color="black">
            <pre>{{news.body[:100]}}</pre>
        </font>
        <!-- 发表时间 -->
        <font size="3" color="black" style="float:right; width:100px">{{moment(news.timestamp).fromNow()}}</font><br>
        </div>
    {% endfor %}

    <div align="center">
        {% import 'macro/macro.html' as macro %}
        {{macro.pagination_widget(paginate, 'main.all_news')}}
    </div>
{% endblock %}

app/templates/main/edit_user.html
<!--在app/templates下找base.html-->
{% extends 'base.html' %}

{% block page_content%}
    <h3>用户编辑</h3>
{% endblock %}
{% block page_content1 %}
    {% import 'bootstrap/wtf.html' as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/main/index.html
<!---->
{% extends 'base.html' %}

<!-- 实现块 -->
{% block page_content %}
    <h2><small>Dear</small>&nbsp;{{current_user.name}}</h2><br>
    <h4>前不见古人，后不见来者。念天地之悠悠，独怆然而涕下。 <br></h4>
{% endblock %}
{% block page_content1 %}
<img src="../../static/images/timg.jpg" />
{% endblock %}


app/templates/main/news.html
<!--在app/templates下找base.html-->
{% import "bootstrap/wtf.html" as wtf %}
{% extends 'base.html' %}

{% block page_content%}
    <h2><small>Dear</small>&nbsp;&nbsp;{{current_user.name}}</h2>
    <a href="{{url_for('main.post_news')}}" class="btn btn-default">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    </a>
{% endblock %}

{% block page_content1 %}
    <div class="page-header">
        <!-- 诗词题目 -->
        <font size="4" color="#191970" style="margin-right: 300px;">{{news.title}}</font>
        <!-- 发表时间 -->
        <br><font size="3" color="black" style="float:right">{{moment(news.timestamp).fromNow()}}</font>
        <font size="3" color="#dc143c" style="margin-right: 30px;">
                <a href="{{url_for('main.delete_news', nid = news.id)}}" style="float:right; width:100px">
                    删除
                </a>
        </font>
        <!-- 发表用户 -->
        <font size="3" color="black" style="margin-right: 100px;">
            <a href="{{url_for('main.user_info', id = news.user.id)}}" style="float:right; width:100px">
                {{news.user.name}}
            </a>
        </font>
        <!-- 文章诗词 -->
        <br><font size="3" color="black">{{news.body}}</font>
        <br><br><font size="3" color="black" style="margin-left: 0px;">
            <a href = "{{ url_for('main.news',nid = news.id,has_form = True)}}">
                 评论
            </a>
        </font>
        <font size="3" color="black" style="margin-left: 30px;">
            <a href = "{{ url_for('main.news',nid = news.id)}}">
                 收起
            </a>
        </font>
        {% if has_comment == "True" %}
            {{ wtf.quick_form(form) }}
        {% endif%}

    </div>
    {% for news in comment %}
        <div class="alert alert-warning" role="alert">
            <font size="3" color="#191970" style="margin-right: 300px;">
                {{news.title}}&nbsp;&nbsp;

                {{news}}楼
                <a href="{{url_for('main.delete_comment', cid = news.id)}}" style="float:right">删除评论</a>
                <!-- 发表时间 -->
                <font size="3" color="black" style="float:right; width:100px">{{moment(news.timestamp).fromNow()}}</font>
            </font>
            <!-- 评论内容 -->
            <font size="3" color="black">
                <br>
                评论：{{news.body[:100]}}
            </font>
        </div>

    {% endfor %}


<!--<div class="alert alert-success" role="alert">1</div>-->
<!--<div class="alert alert-info" role="alert">2</div>-->
<!--<div class="alert alert-warning" role="alert">3</div>-->
<!--<div class="alert alert-danger" role="alert">4</div>-->
{% endblock %}

app/templates/main/post_news.html
{% extends 'base.html' %}

{% block page_content %}
<h3>发表诗词</h3>
{% endblock %}

{% block page_content1 %}
    {% import 'bootstrap/wtf.html' as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/main/user_info.html
{% extends 'base.html' %}

{% block page_content %}
<h2><small>欢迎登录!</small>&nbsp;&nbsp;{{current_user.name}}</h2>
{% endblock %}

{% block page_content1 %}
<div class="alert alert-success" role="alert">
<h4>

    昵称：{{user.name}}
    {% if current_user.if_follower_of(user) %}&nbsp;&nbsp;&nbsp;
        <a class="btn btn-danger" href="{{url_for('main.unfollow', id=user.id)}}">
            <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
        </a>
    {% else %}&nbsp;&nbsp;&nbsp;
        <a class="btn btn-info" href="{{url_for('main.follow', id=user.id)}}">
            <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
        </a>
    {% endif %}
    <a class="btn badge" href="{{url_for('main.all_followers', id=user.id)}}">
        粉丝数量 {{user.followers.count() }}
    </a>
</h4>
<h4>邮箱：{{user.email}}</h4>
<br><h4>签名：{{user.about_me}}</h4>
<h4>位置：
    <a href="http://www.baidu.com/s?wd={{user.location}}">
        {{user.location}}
    </a>
</h4>
<h4>身份：{{user.role.name}}</h4>
<h4>邮箱验证：
    {% if user.confirmed %}
    已验证
    {% else %}
    未验证
    {% endif %}
</h4>
<h4>注册时间：{{moment(user.register_time).format('LLL')}}</h4>
<h4>最近访问：{{moment(user.access_time).fromNow()}}</h4><br>
</div>
<!-- 用户链接资料 -->
<!-- 判断超级用户 -->
{% if current_user.is_admin() %}
    <a href="{{url_for('manager.edit_user', id=user.id)}}" class="btn btn-warning">编辑用户</a>
<!-- 普通用户 -->
{% else %}
    {% if current_user == user %}
        <a href="{{url_for('main.edit_user')}}" class="btn btn-info">编辑用户</a>
    {% endif %}
{% endif %}

{% endblock %}